[[plugins]]
package = "./plugins/success"

[[plugins]]
package = "./plugins/failed_plugin"

[[plugins]]
package = "./plugins/failed_plugin2"

[[plugins]]
package = "./plugins/failed_build"

[[plugins]]
package = "./plugins/failed_build2"
